### ISSUE TITLE
phpmyadmin not found

### ISSUE THREAD

**Issue by dsgnr** [ericmann/vvv-apache#16] opened 2015-11-21 14:58 UTC
Just completed a new install using vvv-apache with and the database-admin is not found when trying to access phpmyadmin via vvv.dev. The default local.wordpress-trunk.dev install site still works as expected.

**Comment by ericmann** [comment] 2015-11-21 16:46
Duplicate of #15

**Closed as completed by ericmann** 2015-11-21 16:46 UTC
